spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # Prints SQL statements to the console
    show-sql: true
    hibernate:
      # Manages database schema generation
      ddl-auto: update
    properties:
      hibernate:
        # Formats the printed SQL for better readability
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081

management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health

resilience4j:
  circuitbreaker:
    instance:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThresold: 50
        minimumNumerOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED




